---
apiVersion: networkservicemesh.io/v1alpha1
kind: NetworkService
metadata:
  name: icmp-responder
spec:
  payload: IP
  matches:
    - match:
      route:
        - destination:
          destinationSelector:
            app: ucnf-endpoint
