# Default values for mysql-slave.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

mysql:
  rootPassword: test
  replicationUser: demo
  replicationPassword: demo
  replicationMaster: mysql-master

nsm:
  ns: vl3-service
  servicename: "mysql-slave"
  serviceport: "3306"

replicaCount: 1

image:
  repository: tiswanso/mysql-slave
  tag: test
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3306

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
