---
apiVersion: v1
kind: Service
metadata:
  name: db-orchestrator
  labels:
    app: db-orchestrator
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: db-orchestrator
  type: LoadBalancer
