---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vl3-nse-ucnf
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      networkservicemesh.io/app: "vl3-nse-ucnf"
      networkservicemesh.io/impl: "vl3-service"
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "vl3-nse-ucnf"
        networkservicemesh.io/impl: "vl3-service"
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: vl3-nse
          image: tiswanso/vl3_ucnf-vl3-nse:unified_api
          imagePullPolicy: Always
          env:
            - name: ENDPOINT_NETWORK_SERVICE
              value: "vl3-service"
            - name: ENDPOINT_LABELS
              value: "app=vl3-nse-ucnf"
            - name: TRACER_ENABLED
              value: "true"
            - name: JAEGER_SERVICE_HOST
              value: jaeger.nsm-system
            - name: JAEGER_SERVICE_PORT_JAEGER
              value: "6831"
            - name: JAEGER_AGENT_HOST
              value: jaeger.nsm-system
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: NSREGISTRY_ADDR
              value: "nsmgr.nsm-system"
            - name: NSREGISTRY_PORT
              value: "5000"
            - name: NSE_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NSM_REMOTE_NS_IP_LIST
              valueFrom:
                configMapKeyRef:
                  name: nsm-vl3
                  key: remote.ip_list
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: true
          resources:
            limits:
              networkservicemesh.io/socket: 1
          volumeMounts:
            - mountPath: /etc/universal-cnf/config.yaml
              subPath: config.yaml
              name: universal-cnf-config-volume
      volumes:
        - name: universal-cnf-config-volume
          configMap:
            name: universal-cnf-vl3
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: universal-cnf-vl3
data:
  config.yaml: |
    endpoints:
    - name: "vl3-service"
      labels:
        app: "vl3-nse-ucnf"
      ipam:
        prefixpool: "172.31.0.0/16"
        routes: []
      ifname: "endpoint0"
