---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kiknos-vpp-cfg
data:
  vpp.conf: |
    unix {
      nodaemon
      cli-listen /run/vpp/cli.sock
      cli-no-pager
      poll-sleep-usec 1000
    }
    punt {
      socket /etc/vpp/punt.sock
    }
    socksvr {
      default
    }
    statseg {
      default
    }
    plugins {
      plugin dpdk_plugin.so {
        disable
      }
    }