apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app}}-v1-service
  labels:
    app: {{.Values.app}}-v1
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: {{.Values.app}}-v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.app}}-v1
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.app}}-v1
      version: v1
  template:
    metadata:
      labels:
        app: {{.Values.app}}-v1
        version: v1
    spec:
      containers:
      - name: helloworld
        image: docker.io/istio/examples-helloworld-v1
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
