apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app}}-v2-service
  labels:
    app: {{.Values.app}}-v2
spec:
  ports:
    - port: 5000
      name: http
  selector:
    app: {{.Values.app}}-v2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.app}}-v2
  labels:
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.app}}-v2
      version: v2
  template:
    metadata:
      labels:
        app: {{.Values.app}}-v2
        version: v2
    spec:
      containers:
        - name: helloworld
          image: docker.io/istio/examples-helloworld-v2
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: IfNotPresent #Always
          ports:
            - containerPort: 5000
